#!/bin/bash
#
# Usage: ./uninstall-dkms

KVERSION=`uname -r`
DKMS_STATUS_OUTPUT_RE="^\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^:]+):(.*)$"

# Unloading module
if (lsmod | grep v4l2loopback_dc); then
    echo "Unloading module"
    rmmod v4l2loopback_dc
fi

# DKMS module
dkms status| grep v4l2loopback_dc | grep ${KVERSION} | while read LINE; do
    if [[ "${LINE}" =~ ${DKMS_STATUS_OUTPUT_RE} ]] && module="${BASH_REMATCH[1]}" && version="${BASH_REMATCH[2]}"  && kversion="${BASH_REMATCH[3]}"  && arch="${BASH_REMATCH[4]}" && status="${BASH_REMATCH[5]}"; then
        echo "De-registering as DKMS module v4l2loopback_dc version ${version} from kernel ${kversion}..."
        dkms remove v4l2loopback_dc/${version} -k ${kversion}
        if [ -d "/usr/src/v4l2loopback_dc-${version}" ]; then
            echo "Removing v4l2loopback_dc version ${version} module source in /usr/src"
            rm -Rf "/usr/src/v4l2loopback_dc-${version}"
        fi
    fi
done

# Module configuration
if [ -f "/etc/modprobe.d/droidcam.conf" ]; then
    echo "Removing module config"
    rm /etc/modprobe.d/droidcam.conf
fi

# Removing droidcam binaries
if [ -f "/usr/bin/droidcam" ]; then
    echo "Removing droidcam binary"
    rm /usr/bin/droidcam
fi
if [ -f "/usr/bin/droidcam-cli" ]; then
    echo "Removing droidcam-cli binary"
    rm /usr/bin/droidcam-cli
fi

