#!/bin/bash
#

# Remove droidcam files
sudo rmmod v4l2loopback_dc
sudo rm -f /usr/bin/droidcam*
sudo rm -f /lib/modules/`uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko

etc_modules() {
	# Remove droidcam reference in /etc/modules
	cat /etc/modules | egrep -v "^(videodev|v4l2loopback_dc)" > /tmp/.etc.modules
	prevperm=`stat -c %a /etc/modules`
	sudo mv /tmp/.etc.modules /etc/modules
	sudo chmod $prevperm /etc/modules
}

[[ -e "/etc/modules" ]] && etc_modules
rm -f /etc/modprobe.d/droidcam.conf || true
rm -f /etc/modules-load.d/droidcam.conf || true
echo "done"
